# Generated by Django 5.2.9 on 2026-06-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
